### ISSUE TITLE
flutter support

### ISSUE THREAD

**Issue by y3l1n4ung** [chenxuewei-ihealth/ihealthlabs-sdk-docs#9]
As a developer interested in integrating iHealth functionality into Flutter applications, having official Flutter support and clear plugin creation guidelines would greatly benefit the development community. Could you please provide information on when Flutter support will be available or direct me to resources that can guide me in creating my own plugin for iHealth integration? Thank you for your attention to this matter.

**Comment by chenxuewei-ihealth** [comment]
Thank you for your interest in the SDK. Currently we do not support the Flutter SDK, if you have a request about buying Flutter SDK custom development, you can contact our sales staff:
Us sales: sales@ihealthlabs.com
European Sales: p.le@ihealthlabs.com
Other regions: sdk@ihealthlabs.com.cn
